import { useNavigate } from 'react-router-dom'
import { useAnalysis } from '../context/AnalysisContext'
import { FileText, Download, AlertTriangle } from 'lucide-react'

export default function ReportPage() {
    const { result } = useAnalysis()
    const navigate = useNavigate()

    if (!result) return (
        <div className="flex flex-col items-center justify-center min-h-[80vh] animate-fadeIn">
            <p className="text-lg mb-4" style={{ color: 'var(--color-text-muted)' }}>No analysis loaded</p>
            <button onClick={() => navigate('/analyze')} className="btn-accent">Upload CSV</button>
        </div>
    )

    const accounts = result.suspicious_accounts || []
    const rings = result.fraud_rings || []
    const summary = result.summary || {}

    const downloadJSON = () => {
        const a = Object.assign(document.createElement('a'), {
            href: URL.createObjectURL(new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' })),
            download: `mulenet_SAR_report_${Date.now()}.json`
        })
        a.click()
    }

    return (
        <div className="max-w-[900px] mx-auto px-6 py-6 animate-fadeIn">
            <div className="flex items-center justify-between mb-6">
                <h1 className="text-2xl font-bold" style={{ color: 'var(--color-text-primary)' }}>
                    <FileText className="w-6 h-6 inline mr-2" style={{ color: 'var(--color-warning)' }} />
                    SAR Report Preview
                </h1>
                <button onClick={downloadJSON} className="btn-success flex items-center gap-2">
                    <Download className="w-4 h-4" /> Download JSON
                </button>
            </div>

            {/* Report Document */}
            <div className="card-dark space-y-6" style={{ fontFamily: 'var(--font-family-sans)' }}>
                {/* Header */}
                <div className="text-center pb-4" style={{ borderBottom: '2px solid var(--color-accent)' }}>
                    <h2 className="text-xl font-black" style={{ color: 'var(--color-accent)' }}>
                        SUSPICIOUS ACTIVITY REPORT
                    </h2>
                    <p className="text-xs mt-1" style={{ color: 'var(--color-text-muted)' }}>
                        Generated by MuleNet Financial Forensics Engine · {new Date().toLocaleString()}
                    </p>
                </div>

                {/* Executive Summary */}
                <section>
                    <h3 className="text-sm font-bold mb-2 uppercase tracking-wider" style={{ color: 'var(--color-blue)' }}>
                        Executive Summary
                    </h3>
                    <p className="text-sm leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>
                        Analysis of {summary.total_accounts_analyzed?.toLocaleString() || 0} accounts identified{' '}
                        <strong style={{ color: 'var(--color-accent)' }}>{summary.suspicious_accounts_flagged || 0} suspicious accounts</strong>{' '}
                        across <strong style={{ color: 'var(--color-warning)' }}>{summary.fraud_rings_detected || 0} fraud rings</strong>.
                        Processing completed in {summary.processing_time_seconds || 0} seconds.
                    </p>
                </section>

                {/* Top Rings */}
                <section>
                    <h3 className="text-sm font-bold mb-3 uppercase tracking-wider" style={{ color: 'var(--color-blue)' }}>
                        Detected Fraud Rings ({rings.length})
                    </h3>
                    <div className="space-y-2">
                        {rings.slice(0, 10).map(r => (
                            <div key={r.ring_id} className="flex items-center gap-4 py-2 px-3 rounded-lg"
                                style={{ background: 'var(--color-panel-light)', border: '1px solid var(--color-panel-border)' }}>
                                <span className="mono font-bold text-xs" style={{ color: 'var(--color-accent)' }}>{r.ring_id}</span>
                                <span className="badge-blue text-[10px]">{r.pattern_type}</span>
                                <span className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                                    {r.member_accounts?.length} members
                                </span>
                                <span className="ml-auto text-xs font-bold" style={{ color: r.risk_score >= 80 ? 'var(--color-accent)' : 'var(--color-warning)' }}>
                                    Risk: {r.risk_score}
                                </span>
                            </div>
                        ))}
                        {rings.length > 10 && (
                            <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                                ... and {rings.length - 10} more rings
                            </p>
                        )}
                    </div>
                </section>

                {/* Top Suspicious Accounts */}
                <section>
                    <h3 className="text-sm font-bold mb-3 uppercase tracking-wider" style={{ color: 'var(--color-blue)' }}>
                        Top Suspicious Accounts
                    </h3>
                    <div className="space-y-2">
                        {accounts.slice(0, 15).map(a => (
                            <div key={a.account_id} className="py-2 px-3 rounded-lg"
                                style={{ background: 'var(--color-panel-light)', border: '1px solid var(--color-panel-border)' }}>
                                <div className="flex items-center gap-3">
                                    <span className="mono font-bold text-xs" style={{ color: 'var(--color-accent)' }}>
                                        {a.account_id}
                                    </span>
                                    <span className="text-xs font-black mono" style={{
                                        color: a.suspicion_score >= 80 ? '#e63946' : a.suspicion_score >= 50 ? '#f4a261' : '#fbbf24'
                                    }}>{a.suspicion_score}/100</span>
                                    <span className="mono text-[10px]" style={{ color: 'var(--color-blue)' }}>{a.ring_id}</span>
                                </div>
                                <div className="flex flex-wrap gap-1 mt-1">
                                    {a.detected_patterns?.map(p => (
                                        <span key={p} className="text-[10px] mono px-1.5 py-0.5 rounded"
                                            style={{ background: 'var(--color-bg)', color: 'var(--color-text-muted)', border: '1px solid var(--color-panel-border)' }}>
                                            {p}
                                        </span>
                                    ))}
                                </div>
                            </div>
                        ))}
                    </div>
                </section>

                {/* Methodology */}
                <section>
                    <h3 className="text-sm font-bold mb-2 uppercase tracking-wider" style={{ color: 'var(--color-blue)' }}>
                        Methodology
                    </h3>
                    <ul className="text-xs space-y-1 list-disc list-inside" style={{ color: 'var(--color-text-secondary)' }}>
                        <li>Johnson's Cycle Detection Algorithm (length-bounded simple cycles)</li>
                        <li>Fan-in/Fan-out Smurfing Detection with 72-hour sliding window</li>
                        <li>Shell Account Detection via betweenness centrality + pass-through ratio</li>
                        <li>Benford's Law digit distribution analysis (chi-square test)</li>
                        <li>Merchant & Payroll whitelist to minimize false positives</li>
                    </ul>
                </section>
            </div>
        </div>
    )
}
